name: Publish Template

on:
  workflow_run:
    workflows: ["SonarQube Cloud"]
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Pack Template
      run: dotnet pack -o ./nupkg --configuration Release

  publish:
    uses: .github/workflows/publish-nuget.yml@main
    with:
      package_path: ./nupkg/*.nupkg

