name: Publish Template

on:
  workflow_run:
    workflows: ["SonarQube Cloud"]
    types:
      - completed

jobs:
  build-and-publish:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Pack Template
      run: dotnet pack -o ./nupkg --configuration Release

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

